# servicecomb service center
apiVersion: v1
kind: Pod
metadata:
  name: servicecenter
  labels:
    app: servicecomb
spec:
  containers:
    - name: servicecenter
      image: servicecomb/service-center:1.0.0-m1
      ports:
        - containerPort: 30100
#      resources:
#        limits:
#          cpu: "1"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: service-center
spec:
  selector:
    app: servicecomb
  ports:
  - protocol: TCP
    nodePort: 30100
    port: 30100
    targetPort: 30100
  type: NodePort




---
# server
apiVersion: v1
kind: Pod
metadata:
  name: server-mesher
  labels:
    app: perf
    version: 0.0.1
spec:
  containers:
    - name: server
      image: xiaoliang/server-go
      ports:
        - containerPort: 9999
#      resources:
#        limits:
#          cpu: "1"
    - name: mesher
      image: gochassis/mesher
      args:
        - --service-ports
        - rest:9999
      env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSE_REGISTRY_ADDR
          value: http://service-center.default:30100
        - name: SERVICE_PORTS
          value: rest:9999
      ports:
        - containerPort: 30101 # proxy
        - containerPort: 30102 # admin API
        - containerPort: 6060 #pprof debug port
#      resources:
#          limits:
#            cpu: "2"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: service-mesher
spec:
  selector:
    app: perf
  ports:
  - protocol: TCP
    name: mesher
    port: 30115
    nodePort: 30115
    targetPort: 30101
  - protocol: TCP
    name: server
    port: 30114
    nodePort: 30114
    targetPort: 9999
  type: NodePort


---
#client
apiVersion: v1
kind: Pod
metadata:
  name: client-mesher
  labels:
    app: client-mesher
    version: 0.0.1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - perf
        topologyKey: kubernetes.io/hostname
  containers:
    - name: client
      image: thanda/client:latest
      env:
        - name: TARGET
          value: http://server-mesher/
        - name: http_proxy
          value: http://127.0.0.1:30101/
      ports:
        - containerPort: 9000
#      resources:
#        limits:
#          cpu: "0.5"
    - name: mesher
      image: gochassis/mesher
      env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSE_REGISTRY_ADDR
          value: http://service-center.default:30100
      ports:
        - containerPort: 30101
        - containerPort: 30102
        - containerPort: 6060
#      resources:
#          limits:
#            cpu: "0.5"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: client-mesher
spec:
  selector:
    app: client-mesher
  ports:
  - protocol: TCP
    name: client
    port: 30117
    nodePort: 30117
    targetPort: 9000
  - protocol: TCP
    name: client-mesher
    port: 30116
    nodePort: 30116
    targetPort: 30101
  type: NodePort